[project]
name = "labs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pip>=25.3",
    "pyfakefs==5.10.1",
    "pytest==8.4.2",
    "setuptools>=80.9.0",
]